<a href="https://colab.research.google.com/github/rkirandatta16-art/Data-analysis-/blob/main/25bds0101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:

df1SE = pd.DataFrame({
    'player jersey no': [10, 14, 15, 22, 33, 11, 12, 18, 19],
    'runs' : [61, 68, 81, 70, 30, 92, 96, 84, 84]})
df2SE = pd.DataFrame({
    'player jersey no': [3, 5, 7, 9, 11, 13, 15, 17, 18, 21, 23, 25, 27],
    'runs': [97, 33, 12, 31, 62, 11, 97, 39, 48, 11, 73, 69, 30]})
df1ML = pd.DataFrame({
    'player jersey no': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
    'runs' : [42, 85, 67, 31, 98, 58, 69, 51, 68, 89, 24, 71, 71, 56, 71]})
df2ML = pd.DataFrame({
    'player jersey no': [1, 3, 5, 12, 14, 15, 16, 17, 18, 19],
    'runs': [60, 64, 73, 12, 68, 16, 30, 82, 48, 27]})

In [ ]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = pd.concat([dfML, dfSE], axis=1)
df

    player jersey no  runs  player jersey no  runs
0                  2    42              10.0  61.0
1                  4    85              14.0  24.0
2                  6    67              15.0  81.0
3                  8    31              22.0  70.0
4                 10    98              33.0  30.0
5                 12    58              11.0  92.0
6                 14    68              12.0  96.0
7                 16    51              18.0  84.0
8                 18    69              19.0  84.0
9                 20    89               3.0  97.0
10                22    24               5.0  33.0
11                24    71               7.0  12.0
12                26    71               9.0  31.0
13                28    56              11.0  62.0
14                30    71              13.0  11.0
15                 1    60              15.0  97.0
16                 3    64              17.0  39.0
17                 5    73              18.0  48.0
18                12    12              21.0  11.0
19                14    68              23.0  73.0
20                15    16              25.0  69.0
21                16    30              27.0  30.0
22                17    82               NaN   NaN
23                18    48               NaN   NaN
24                19    27               NaN   NaN

In [ ]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='inner')
df

   player jersey no  runs
0                14    68
1                18    48

In [ ]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='left')
df

    player jersey no  runs
0                 10    61
1                 14    24
2                 15    81
3                 22    70
4                 33    30
5                 11    92
6                 12    96
7                 18    84
8                 19    84
9                  3    97
10                 5    33
11                 7    12
12                 9    31
13                11    62
14                13    11
15                15    97
16                17    39
17                18    48
18                21    11
19                23    73
20                25    69
21                27    30

In [ ]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='right')
df

    player jersey no  runs
0                  2    42
1                  4    85
2                  6    67
3                  8    31
4                 10    98
5                 12    58
6                 14    68
7                 16    51
8                 18    69
9                 20    89
10                22    24
11                24    71
12                26    71
13                28    56
14                30    71
15                 1    60
16                 3    64
17                 5    73
18                12    12
19                14    60
20                15    16
21                16    30
22                17    82
23                18    48
24                19    27

In [ ]:
import numpy as np
data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
dframe1

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [ ]:
stacked = dframe1.stack()
stacked

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

In [ ]:
stacked.unstack()

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [ ]:
series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
frame2.unstack()

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN